# Generated by Django 4.0.4 on 2022-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_done_on',
            field=models.DateTimeField(verbose_name='22-May-2022'),
        ),
    ]
