# Generated by Django 4.0.4 on 2022-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_expense_expense_done_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_done_on',
            field=models.DateTimeField(),
        ),
    ]
